version: '3.9'
services:
  php_env:
    build: .
    volumes:
     - ./:/var/www/html
    ports:
      - 3000:80
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: laxman
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1